"""empty message

Revision ID: 28ce4b4e1468
Revises: 2bb32dea3099
Create Date: 2016-03-02 22:25:40.258950

"""

# revision identifiers, used by Alembic.
revision = '28ce4b4e1468'
down_revision = '2bb32dea3099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
