"""empty message

Revision ID: 2bb32dea3099
Revises: 36c3e9686e09
Create Date: 2016-03-02 22:22:35.882933

"""

# revision identifiers, used by Alembic.
revision = '2bb32dea3099'
down_revision = '36c3e9686e09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
