"""empty message

Revision ID: 35489e9efb7a
Revises: 28ce4b4e1468
Create Date: 2016-03-02 22:31:50.177131

"""

# revision identifiers, used by Alembic.
revision = '35489e9efb7a'
down_revision = '28ce4b4e1468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
